
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    sudo apt-get -y install libgeos-dev proj-bin libproj-dev libudunits2-dev libmpich-dev libnetcdf-dev
    pip install cython requests
    pip install ./
    python -c "import ILAMB; print('ILAMB v%s successfully installed' % (ILAMB.__version__))"
  displayName: 'Install dependencies'

- script: |
    cd test
    export ILAMB_ROOT=./
    ilamb-fetch --remote_root https://www.ilamb.org/Test-Data --no-check-certificate -y
    ilamb-run --config test.cfg --model_root MODELS --regions global shsa
    python score_diff.py scores_test.csv.gold _build/scores.csv
  displayName: 'Run tests'